# platform :ios, '9.0'

target 'CareemMovies' do
  use_frameworks!

  # Pods for App
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'

  target 'CareemMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
